version: '3.9'

services:
  api:
    ports:
      # Exposes application port.
    - "8000:8000"
    volumes:
      # Adds current directory as volume.
    - .:/app/src/
    environment:
      # Enables autoreload.
      NSAPP_RELOAD: "True"

  dramatiq:
    # Runs dramatiq worker with live reload.
    command: dramatiq ns_app.workers.tasks  --processes 1 --threads 1 --watch /app/src/ns_app/workers/

  spark:
    ports:
    - '8080:8080'

  spark-worker:
    ports:
    - '8081:8081'
    - '4040:4040'
